module Priority
using PyCall,Distributions,DataStructures
@pyimport networkx as nx
@pyimport matplotlib.pyplot as plt
# package code goes here
export average_bw,reach_stable_time,order_parameter,percolation,critical_threshold,correlation
export correlation_length,betweenness_distribution,average_betweenness,pathlength_and_travelingtime_distribution
export average_pathlength_and_travelingtime
using Priority_Scalefree
end # module
